//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dvision_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleDetails
    {
        public int SDetailID { get; set; }
        public int SDetailSaleID { get; set; }
        public int SDetailProductID { get; set; }
        public Nullable<decimal> SDetailTOTAL { get; set; }
        public Nullable<int> SDetailQuantity { get; set; }
        public Nullable<decimal> SDetailPrice { get; set; }
        public string SDetailName { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Sales Sales { get; set; }
    }
}
